---
output:
  github_document:
    html_preview: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# Extrair  dados sobre COVID da Universidade Johns Hopkins
#### Atualizado em:
```{r echo=FALSE}
print(Sys.Date())
```

## Transformando dados e calculando campos importantes para análise
A Universidade de Johns Hopkins mantem um dos mais famosos levantamentos sobre a epidemia causada pelo Corona Vírus. Eles disponibilizam esses dados em um repositório do [github](https://github.com/CSSEGISandData/COVID-19).

Entretanto, o formato dos dados não é dos mais adequados para análise. Cada data é uma nova coluna. Além disso, dados importantes náo estáo pré-calculados nessa base (o que é compreensível: é um repositório). 

O arquivo CSV que criei (e o código que o gerou, em R) possue algumas vantagens em relação ao disponibilizado pela U. J. Hopkins:

+ Base de dados em formato long

+ Traz o número de **novos casos** e **novas mortes**

+ Traz o total de dias desde o **primeiro caso** para cada data

+ Traz o total de dias desde a **primeira morte** para cada data

Os dados fornecidos pela refereida universidade estão no nível do estado/província. Entretanto, para muitos países náo há quebra por província (como é o caso do *Brasi*), mas apenas o agregado nacional. Seria válido um esforço de brasileiros para levantar esses dados e fornecê-los aos pesquisadores de Johns Hopkins. 

É importante salientar que o total de *casos confirmados* é sabidamente falho, na medida que diferentes países tem diferentes capacidades de testagens. Consequentemente, só calcule a taxa de mortalidade de países tendo total ciência das graves limitações desses dados. A estatística de mortes, embora também possa contem errros de medição, é bem mais confiável. 

Favor referenciar o meu [linkedin](https://www.linkedin.com/in/saulo-said-b43356a1/) quando utilizar os dados.
